<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository {
    
      
    public function getParent(){
        $qb = $this->getEntityManager()
                ->createQueryBuilder()
                ->select('c')
                ->from('AppBundle:Comment', 'c')
                ->where('c.idParent IS NULL')
                ->getQuery();
        $result = $qb->getScalarResult();
        return $result;
    }
    
    public function getChildByIdParent($id_parent){
         $qb = $this->getEntityManager()
                ->createQueryBuilder()
                ->select('c')
                ->from('AppBundle:Comment', 'c')            
                ->where('c.idParent= :idp')
                ->setParameter('idp', $id_parent)
                ->getQuery();
        $result = $qb->getScalarResult();
        return $result;
    }
    
    public function asChild(array $ids){
        $qb = $this->getEntityManager()
                ->createQueryBuilder()
                ->select('c.idParent')
                ->from('AppBundle:Comment', 'c')
                ->where('c.idParent IN (' . implode(',',$ids) . ')')
                ->groupBy('c.idParent')
                ->getQuery();
        $result = $qb->getScalarResult();
        $array = array();
        foreach ($result as $row){
            $array[] = $row['idParent'];
        }
        return $array;                
    }   
}
